const chatRooms = [
    { id: 'all-music', title: '🎵 All Music 🎶' },
    { id: 'live-concert', title: '🎤 Live Concerts 🎸' },
    { id: 'rock', title: 'Rock' },
    { id: 'pop', title: 'Pop' },
    { id: 'popular', title: 'Popular' },
    { id: 'hip-hop', title: 'Hip hop' },
    { id: 'jazz', title: 'Jazz' },
    { id: 'rhythm-and-blues', title: 'Rhythm & Blues' },
    { id: 'electronic', title: 'Electronic' },
    { id: 'country', title: 'Country' },
    { id: 'blues', title: 'Blues' },
    { id: 'classical', title: 'Classical' },
    { id: 'heavy-metal', title: 'Heavy Metal' },
    { id: 'electronic-dance', title: 'Electronic Dance' },
    { id: 'dance', title: 'Dance' },
    { id: 'world', title: 'World' },
    { id: 'funk', title: 'Funk' },
    { id: 'soul', title: 'Soul' },
    { id: 'alternative-rock', title: 'Alternative Rock' },
    { id: 'punk-rock', title: 'Punk Rock' },
    { id: 'reggae', title: 'Reggae' },
    { id: 'indie-rock', title: 'Indie Rock' },
    { id: 'music-of-latin-america', title: 'Music of Latin America' },
    { id: 'folk', title: 'Folk' },
    { id: 'pop-rock', title: 'Pop Rock' },
    { id: 'latin', title: 'Latin' },
    { id: 'easy-listening', title: 'Easy Listening' },
    { id: 'new-age', title: 'New-age' },
    { id: 'disco', title: 'Disco' },
    { id: 'techno', title: 'Techno' },
    { id: 'musical-theatre', title: 'Musical Theatre' },
    { id: 'singing', title: 'Singing' },
    { id: 'house', title: 'House' },
    { id: 'ska', title: 'Ska' },
    { id: 'instrumental', title: 'Instrumental' },
    { id: 'dubstep', title: 'Dubstep' },
    { id: 'electro', title: 'Electro' },
    { id: 'experimental', title: 'Experimental' },
    { id: 'ambient', title: 'Ambient' },
    { id: 'gospel', title: 'Gospel' },
    { id: 'music-of-the-united-states', title: 'United States Music' },
    { id: 'vocal', title: 'Vocal' },
    { id: 'contemporary-r-b', title: 'Contemporary R&B' },
    { id: 'psychedelic-rock', title: 'Psychedelic Rock' },
    { id: 'trance', title: 'Trance' },
    { id: 'hardcore-punk', title: 'Hardcore Punk' },
    { id: 'new-wave', title: 'New Wave' },
    { id: 'children', title: 'Children\'s' },
    { id: 'opera', title: 'Opera' },
    { id: 'salsa', title: 'Salsa' },
    { id: 'industrial', title: 'Industrial' },
    { id: 'progressive-rock', title: 'Progressive Rock' },
];

export { chatRooms };
